### ISSUE TITLE
[1.hello-world] The port value of the app should be mutable

### ISSUE THREAD

**Issue by yanxinyuan** [dapr/samples#100]
## Describe the proposal
In the document, it seems the port of the app can be changed by user. For example, change it to 3001,
```
dapr run --app-id mynode --app-port 3001 --port 3500 node app.js
```
But in the code as below shows, the value of the port seems can't be changed, so user may be confused when run this scenario.
```
const port = 3000;
app.listen(port, () => console.log(`Node App listening on port ${port}!`));
```

**Comment by yanxinyuan** [comment]
fixed in #99

**Comment by trumhemcut** [comment]
I think in the cli, it should use the port of the app using, so the example is quite clear that we will use port 3000.

In real world, I think it should be configurable which both cli & the app will use the same configuration (e.g. via Environment variable), but in the scope of the example I think that's acceptable.

**Comment by ryanvolum** [comment]
The reason the sample uses `const` instead of `let` or `var` is because the port the app runs on is not expected to change once the app is running. As with any sample code, developers are free to change the port to whichever port they like. 

Given that this lacked clarity though, I PRed a quick clarification into the README: #104
