### ISSUE TITLE
How can I run a sample without Docker?

### ISSUE THREAD

**Issue by aloneguid** [dapr/samples#103]
All the samples seem to have Docker as a requirement. I know it's possible to run Dapr without heavy dependencies on edge etc., can you provide a simple example how to do this?

**Comment by trumhemcut** [comment]
If you're run **1.hello-world** example on Mac, then you're just need to install Redis on your machine to get the sample started smoothly. To install Redis, you just run:

```brew install redis```
then run
```redis-server /usr/local/etc/redis.conf``` to start the redis server.

After that, you can run the example without Docker. But I'm highly recommend that you should use Docker & Kubernetes because it's where Dapr are serving its most value.

**Comment by aloneguid** [comment]
No thanks I don't want redis or kubernetes, it's an overkill for 100% applications (just rounding up here) :)

**Comment by ryanvolum** [comment]
Hey @aloneguid. Redis is one of multiple supported pluggable state stores that you can use with Dapr. The samples just use Redis as an example. 

The **1.hello-world** sample demonstrates a couple things, the first of which should work sans any state store at all: 

1. Service discovery - using the Dapr sidecar to invoke one microservice from another one
2. State persistence - using the Dapr sidecar to persist/retrieve state from any of Dapr's supported state stores.

**Comment by ryanvolum** [comment]
@aloneguid, I hope this context helps. For future questions, feel free to use the gitter channel: https://gitter.im/Dapr/samples?at=5db71ad714d55a378590324e
