### ISSUE TITLE
Merge samples 1 and 2 into 1 and create a new sample 2

### ISSUE THREAD

**Issue by artursouza** [dapr/samples#120]
Samples 1 and 2 are tightly coupled and sample 2 does not make much sense without going though sample 1 first. Even though it is the expected behavior, it breaks the previous principle that each test should be independently understood and executed. This proposal is to do the following:

1. Merge samples 1 and 2 into 1.
2. Create a brand new sample 2. (ideas?)

**Comment by ryanvolum** [comment]
Hey @artursouza. At a high level, I agree that we should compress samples one and two. That said, samples one and two are slightly different: Sample 1 has a single (Node) microservice and expects the user to invoke it through the dapr runtime, and sample two has two microservices (Node and Python) where the Python microservice creates events that it sends to the Node app. 

I think ideally we want to show how dapr services invoke each other as the first sample. The reason we didn't do that is because we wanted a five-minutes-to-wow experience. If developers have to run two microservices written in two languages, all of the sudden they're installing a lot more onto their machine to get started (Python, pip, Node, npm, etc.). The friction of setting up environments for different languages is not true in K8s, where containers already have everything they need. 

A couple options as I see them: 
1. Make sample 1 _two Node microservices_, where one invokes the other (minimizing the number of languages needed to run locally). 
2. Make sample 1 a Python and Node microservice (using the same code as sample two), but give readers the option of sending messages to the Node microservice manually instead of requiring them to also run the Python microservice

As with the other samples, we would have standalone instructions and K8s instructions.

**Comment by msfussell** [comment]
I do not have an issue that one follows on from the other. And given that sample 1 is now option 2. above in structure with choices on how to invoke this, then most people will just see sample 2 and doing this in a new environment. Let's leave this as is currently and wait on any feedback from people

**Comment by amanbha** [comment]
Closing it based on sample doc review, this change would not be needed.
