### ISSUE TITLE
HelloWorld sample hangs forever if you request to /order first

### ISSUE THREAD

**Issue by nqbao** [dapr/samples#90]
<img width="1429" alt="Screenshot 2019-10-28 16 41 50" src="https://user-images.githubusercontent.com/177742/67726118-037c3280-f9a2-11e9-99c8-d1c4469e0278.png">

When you first start the helloworld sample, if you request to /order it will hang **forever**
I was just playing around to see the behavior. I'm not sure where to report this, so i just report it here.

Please let me know if you would like me to move this issue to other repo.

## Expected Behavior

The error should be propagated to client.

## Actual Behavior

The client request hangs forever.

## Steps to Reproduce the Problem

Follow the helloworld sample, then execute the `/order` request right after that

```
curl http://localhost:3500/v1.0/invoke/mynode/method/order
```

**Comment by ryanvolum** [comment]
This issue seems to hit on two things: 

1. The hello-world sample lacks expects that state has already been persisted to Redis, and attempts to deserialize the response body of the Redis call. We could wrap the call to Redis in a try/catch block to at least catch the error. I would ask though, @yaron2 is this the desired behavior of a call against a state store missing a key? 

`/order` route FYI:

```js
app.get('/order', (_req, res) => {
    fetch(`${stateUrl}/order`)
        .then((response) => {
            return response.json();
        }).then((orders) => {
            res.send(orders);
        });
});
```
2. Errors from a dapr-enabled microservice don't get propagated up to clients that invoke them. This is also something we could handle in the sample, but that the dapr runtime could also potentially handle. @yaron2 let me know if you have any thoughts here.
